executor: slurm

default-resources:
    mem_mb: 180_000
    gpu: 0
    slurm_account: p0020567
    runtime: 720
    cpus_per_task: 12

restart-times: 0
max-jobs-per-second: 50
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
